INSERT INTO TITLE (ID,DESCRIPTION,OWNER_NAME) VALUES (1,'Lot 1 on Block 1','Jane Doe');
INSERT INTO TITLE (ID,DESCRIPTION,OWNER_NAME) VALUES (2,'Lot 2 on Block 1','Bob Smith');

INSERT INTO OWNER_NAME_HISTORY  (ID, CHANGED_AT  ,OWNER_NAME, TITLE_ID) VALUES (1,CURRENT_TIMESTAMP,'Aruna',1);
INSERT INTO OWNER_NAME_HISTORY  (ID, CHANGED_AT  ,OWNER_NAME, TITLE_ID) VALUES (2,CURRENT_TIMESTAMP,'Sameera',1);
INSERT INTO OWNER_NAME_HISTORY  (ID, CHANGED_AT  ,OWNER_NAME, TITLE_ID) VALUES (3,CURRENT_TIMESTAMP,'Liyanage',1);
INSERT INTO OWNER_NAME_HISTORY  (ID, CHANGED_AT  ,OWNER_NAME, TITLE_ID) VALUES (4,CURRENT_TIMESTAMP,'Jane Doe',1);
INSERT INTO OWNER_NAME_HISTORY  (ID, CHANGED_AT  ,OWNER_NAME, TITLE_ID) VALUES (5,CURRENT_TIMESTAMP,'Bob Smith',2);